kant = int(input("Kerro suorakulmion kanta. "))
kork = int(input("Kerro suorakulmion korkeus. "))
ala = str(kant * kork)
piir = str(kant + kant + kork + kork)
str(ala)
str(piir)
print("Suorakulmion pinta-ala on " +ala+ ".")
print("Suorakulmion piiri on " +piir+ ".")

num1 = int(input("Anna kokonaisluku. "))
num2 = int(input("Anna toinen kokonaisluku. "))
num3 = int(input("Anna vielä kolmas kokonaisluku. "))
summ = str(num1 + num2 + num3)
print("Lukujen summa on " +summ+".")
tul = str(num1 * num2 * num3)
print("Lukujen tulo on " +tul+ ".")
kes = str((num1 + num2 + num3) / 3)
print("Lukujen keskiarvo on " +kes+ ".")

